from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
import os
from datetime import datetime

def generate_report(patient_data, disease, confidence):
   

    os.makedirs("reports", exist_ok=True)

    filename = f"reports/Anaemia_Report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    title_style = styles["Title"]
    title_style.alignment = TA_CENTER

    heading = styles["Heading2"]
    normal = styles["Normal"]

    story = []

    # ---------------- Header ----------------

    story.append(Paragraph("🏥 <b>ABC Hospital</b>", title_style))
    story.append(Paragraph("<b>Anaemia AI Prediction System</b>", title_style))
    story.append(Paragraph("<br/>", normal))

    story.append(
        Paragraph(
            f"<b>Report Generated:</b> {datetime.now().strftime('%d-%m-%Y %I:%M %p')}",
            normal,
        )
    )

    story.append(Paragraph("<hr/>", normal))

    # ---------------- Patient Information ----------------

    story.append(Paragraph("<b>Patient Information</b>", heading))

    story.append(
        Paragraph(
            f"<b>Patient Name:</b> {patient_data.get('Patient Name','')}",
            normal,
        )
    )

    story.append(
        Paragraph(
            f"<b>Patient ID:</b> {patient_data.get('Patient ID','')}",
            normal,
        )
    )

    story.append(
        Paragraph(
            f"<b>Age:</b> {patient_data.get('Age','')}",
            normal,
        )
    )

    story.append(
        Paragraph(
            f"<b>Gender:</b> {patient_data.get('Gender','')}",
            normal,
        )
    )

    story.append(Paragraph("<br/>", normal))

    # ---------------- CBC Results ----------------

    story.append(Paragraph("<b>CBC Test Results</b>", heading))

    skip = ["Patient Name", "Patient ID", "Age", "Gender"]

    for key, value in patient_data.items():

        if key not in skip:
            story.append(
                Paragraph(
                    f"<b>{key}</b> : {value}",
                    normal,
                )
            )

    story.append(Paragraph("<br/>", normal))

    # ---------------- Prediction ----------------

    story.append(Paragraph("<b>AI Prediction</b>", heading))

    story.append(
        Paragraph(
            f"<b>Predicted Disease:</b> {disease}",
            normal,
        )
    )

    story.append(
        Paragraph(
            f"<b>Confidence:</b> {confidence:.2f}%",
            normal,
        )
    )

    story.append(Paragraph("<br/>", normal))

    # ---------------- Diet ----------------

    diets = {

        "Healthy":"Maintain a balanced diet and regular exercise.",

        "Iron deficiency anemia":
        "Increase iron-rich foods such as spinach, beetroot, dates, lentils, red meat and vitamin C fruits.",

        "Macrocytic anemia":
        "Consume foods rich in Vitamin B12 and Folate such as eggs, milk and green vegetables.",

        "Normocytic hypochromic anemia":
        "Eat iron-rich foods and protein-rich meals.",

        "Normocytic normochromic anemia":
        "Maintain a balanced diet and follow physician advice.",

        "Other microcytic anemia":
        "Consult your physician for further investigations.",

        "Thrombocytopenia":
        "Eat Vitamin K rich foods and leafy vegetables.",

        "Leukemia":
        "High protein diet, fruits, hydration and regular medical supervision.",

        "Leukemia with thrombocytopenia":
        "Follow specialist advice and consume soft nutritious foods."
    }

    story.append(Paragraph("<b>Recommended Diet</b>", heading))
    story.append(
        Paragraph(
            diets.get(disease, "Consult your doctor."),
            normal,
        )
    )

    story.append(Paragraph("<br/>", normal))

    # ---------------- Medical Advice ----------------

    story.append(Paragraph("<b>Medical Advice</b>", heading))

    story.append(
        Paragraph(
            "Please consult a qualified physician or hematologist for confirmation of diagnosis. "
            "This AI prediction is intended for educational purposes and should not replace professional medical advice.",
            normal,
        )
    )

    story.append(Paragraph("<br/>", normal))

    story.append(
        Paragraph(
            "<b>Generated by:</b> Anaemia AI Prediction System",
            normal,
        )
    )

    doc.build(story)

    return filename